# Generated by Django 4.0.1 on 2022-01-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=None, upload_to='pics'),
            preserve_default=False,
        ),
    ]
