# Generated by Django 4.0.1 on 2022-01-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.TextField(default='electronics'),
            preserve_default=False,
        ),
    ]
