# Generated by Django 4.0.1 on 2022-01-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_categories_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('electronics', 'electronics'), ('shoes', 'shoes'), ('tshirt', 'tshirt')], max_length=60),
        ),
    ]
