# Generated by Django 4.0.1 on 2022-01-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='Price',
            field=models.IntegerField(default=450),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('electronics', 'electronics'), ('shoes', 'shoes'), ('tshirt', 'tshirt')], max_length=60),
        ),
    ]
