# Generated by Django 4.0.1 on 2022-01-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
