# Generated by Django 4.0.1 on 2022-02-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemdetails',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
