# Generated by Django 4.0.1 on 2022-02-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_order_itemdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='harindamsharma18@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
