# Generated by Django 4.0.1 on 2022-02-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip',
        ),
        migrations.AddField(
            model_name='order',
            name='noofitems',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Accepted', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.IntegerField(default=1500),
            preserve_default=False,
        ),
    ]
