# Generated by Django 4.0.1 on 2022-02-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_order_city_remove_order_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timeoforder',
            field=models.DateField(auto_now_add=True, default='2022-01-20'),
            preserve_default=False,
        ),
    ]
