# Generated by Django 4.0.1 on 2022-02-03 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_order_timeoforder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeoforder',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
