# Generated by Django 4.0.1 on 2022-02-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_order_timeoforder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeoforder',
            field=models.DateField(auto_now_add=True),
        ),
    ]
