# Generated by Django 4.0.1 on 2022-02-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_order_timeoforder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Shoes', 'Shoes'), ("Men's wear", "Men's wear")], max_length=60),
        ),
    ]
