# Generated by Django 4.0.1 on 2022-02-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Women Fashion', 'Women Fashion'), ("Men's wear", "Men's wear")], max_length=60),
        ),
    ]
