# Generated by Django 4.0.1 on 2022-02-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Shoes', 'Shoes'), ('Kids Wear', 'Kids Wear'), ("Men's wear", "Men's wear"), ('Women Fashion', 'Women Fashion')], max_length=60),
        ),
    ]
